### PR TITLE
Create templates folder

### PR DESCRIPTION
**Pull request by lucasvallenet**
## Add templates/ folder

This allows us to have consistency within our projects, mainly when we have a preview feature (with Craft or Prismic for example). With this structure, we can choose to prerender the pages for live content, and disable it in preview mode.

We can now prerender the main pages in server or hybrid mode using `export const prerender = true | false`

### CODE REVIEW

**Review by mcaskill — COMMENTED** [review]
I suppose `About` and `Home` are not the best examples given they are often a unique page layout.

Are there any existing conventions among other Astro boilerplates?

I find `src/templates/Foobar/FoobarTemplate.astro` unnecessarily verbose.

Also, shouldn't the base directory name and file name suffix match the main tag for consistency?

- `src/templates/Foobar/Template.astro`
- `src/templates/Foobar/Layout.astro`
- `src/layouts/Foobar.astro`
- `src/layouts/Foobar/Layout.astro`

**Comment by devenini** [comment]
Love the idea of template components! It's a great way to reduce duplicated code in routes, especially on a multilingual Astro website. I agree with @mcaskill that we can improve the naming, and I also think we could enhance the PR by reorganizing how we could structure our queries.

The structure below is inspired by the [DatoCMS Astro starter kit,](https://github.com/datocms/astro-starter-kit) (see their [BlockImage](https://github.com/datocms/astro-starter-kit/tree/main/src/components/blocks/ImageBlock) for example) specifically in how they manage blocks with fragments. I’ve adapted this structure to also work with templates, making it well-suited for GraphQL projects.

```
/src/
└── /templates/
    └── /About/
        ├── Template.astro
        ├── query.ts
        └── index.ts
```

In this setup, the `index.ts` file is used to simplify imports by serving as an entry point. It exports the `Template.astro` component by default, making it easier to import this component elsewhere without specifying the exact file.

This structure also works well for components or blocks that use GraphQL fragments:

```
/src/
└── /components/
    └── /BlockImage/
        ├── Component.astro
        ├── fragment.ts
        └── index.ts
```

What do you think?

**Comment by Jerek0** [comment]
I really like the idea of template components as well! 👍
It's nice to put those in a separate folder from regular components to improve DX & readability of the project.

@mcaskill's observations are on point: maybe it's not to be used for unique page layouts, we also could improve naming a bit as suggested. 

Since I didn't get the chance to work with GraphQL projects yet, my input may be light but @devenini's suggestions also look good to me ✅

**Comment by lucasvallenet** [comment]
I also think we could improve the naming.
But we should also consider DX in terms of finding the correct file easily.

I'm not convinced to have the same `index.ts` file in every folder to simplify the import, we may have a custom element ts file in the folder aswell.

Maybe something like this ?
```
/src/
└── /components/
    └── /BlockImage/
        ├── index.astro
        ├── styles.scss
        ├── fragment.ts
        └── index.ts
```

**Pull request merged**
